"""Add post update

Revision ID: d2c5db8606e5
Revises: 1b4644b4d1bf
Create Date: 2026-07-30 11:51:29.473745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c5db8606e5'
down_revision = '1b4644b4d1bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_content_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_content_key'))

    op.drop_table('site_content')
    # ### end Alembic commands ###
